splunk/addonfactory-ucc-base-ui

- package.json
- src/main/webapp/components/BaseFormView.jsx
- src/main/webapp/components/CustomControl.jsx
- src/main/webapp/components/CustomMenu.jsx
- src/main/webapp/components/table/CustomTableControl.jsx
- src/main/webapp/components/table/CustomTableRow.jsx
- src/main/webapp/pages/Input/InputPage.jsx
- webpack.config.js
Jira: https://jira.splunk.com/browse/ADDON-37161
Changes:
- Added `{type: "external"}` param support for custom UI extensions (i.e. hook, cell, control, menu, row) in globalConfig to support ESM JS modules (Note: when no type is specified, it will default to requireJS import which was the old way) 
- Added error handling in custom UI extensions so that it does not crash the whole UI in case of any error in the extensions
For details on ESM modules: https://webpack.js.org/guides/ecma-script-modules/
> Support ESM JS module imports for custom UI extensions

- package.json
- webpack.config.js
Bundle `schema.json` and `THIRDPARTY.npm` (notice) along with generated static files for `ucc-gen` to consume.
Note: `license-check` CI should pass after merging: https://github.com/splunk/addonfactory-ucc-base-ui/pull/32
> fix: add `schema.json` and NOTICE in release tarball

- THIRDPARTY.npm
- src/main/webapp/components/table/CustomTable.jsx
- src/main/webapp/pages/Configuration/ConfigurationPage.jsx
**Jira:** https://jira.splunk.com/browse/ADDON-37812
Changes:
- Kept only one-way routing to resolve multiple issues i.e. removed route updates from code
**Description:**
Because of how tabs are displayed (i.e. on tab visit we set CSS `display` property to show/hide them), it will fail to allow edit button click. This is caused when multiple tables tabs are used, both tables present in different tabs will revert URL query param and ultimately blocking the user from editing form. For reference: 
https://github.com/splunk/addonfactory-ucc-base-ui/blob/44576bcde18219085848f2852aa8c07c9fbdcfd1/src/main/webapp/components/table/CustomTable.jsx#L83-L87
We can overcome this by passing a prop that tells the table if it is active or not and only then update query params but that will make …
> fix: keep only one way routing as done in ucc < 5

- src/main/webapp/components/ErrorBoundary.jsx
- src/main/webapp/constants/errorCodes.js
- src/main/webapp/constants/errorCodes.jsx
Jira Link : https://jira.splunk.com/browse/ADDON-37808
- Used a card component in the middle of the page for errors.
- Showed Error Code in footer as that information is not as important to the user as it is to the developer.
- Added a info message in case the Inputs page does not load - that the splunk search heads do not need inputs page.
- Added a redirect to the configuration page os as not to leave the user stranded on the error page.
SS of the page :
> Feature/addon 37808 enhance page errors' UX and UI

- src/main/webapp/pages/Configuration/ConfigurationPage.jsx
- src/main/webapp/pages/Input/InputPage.jsx
Jira: https://jira.splunk.com/browse/ADDON-37999
Description: When a TA does not include the `description` property in the `globalConfig.json` for configuration or inputs page. The schema validation passes because the field is optional but i18n will fail with error because of undefined value and it expects a string literal.
Changes:
- I checked all the occurrences of `_()` of i18n in the codebase and added an optional empty string in case the field is optional in `globalConfig.json` or can be undefined.
> fix: pass empty string to i18n if the field is optional

- src/main/webapp/components/BaseFormView.jsx
- src/main/webapp/schema/schema.json
Jira: https://jira.splunk.com/browse/ADDON-38644
Changes:
- feat: add support of `required` param in OAuth config
The default value for `required` will be `true` to handle upgrade scenarios. For `false`, will need to be explicit in `globalConfig.json`.
> feat: add support of `required` param in oauth config

- src/main/webapp/components/table/TableExpansionRow.jsx
Jira: https://jira.splunk.com/browse/ADDON-39037
> fix: skip `null` value fields from displaying in table expansion row

- src/main/webapp/schema/schema.json
- src/main/webapp/schema/schemaGenerator.py
This PR marks `apiVersion` as not required in `meta` configuration of globalConfig.json.
This should not break anything in the existing add-ons and `ucc-gen` should work fine with this change.
It will be removed in couple of next releases.
> feat: apiVersion is not required anymore

- src/main/webapp/schema/schema.json
This PR adds a support for custom REST handler module and custom REST handler class. It keeps `restHandlerName` in place to be compatible with the add-ons which are using it.
The idea of the `restHandlerName` is not to generate the REST handler and directly use the one which is provided. For example, check https://github.com/splunk/splunk-add-on-for-crowdstrike-fdr/blob/139048ac9f44ea47e7e3d12531bb7a38eee5cfd2/globalConfig.json#L8. There are only couple of add-ons using this field, so we can potentially migrate them to use `restHandlerModule` and `restHandlerClass` in the future.
The idea of the `restHandlerModule` and `restHandlerClass` is to generate a default REST handler which uses `restHandlerClass` from `restHandlerModule` module instead of the default option (`from …
> feat: support custom REST handlers

- src/main/webapp/pages/Input/InputPage.jsx
Now, the custom menu and style property work well together.
If the `style: "page"` specifies in the globalConfig file, the form will open on the new page; otherwise, it will open in a dialog/modal.
> fix(CODE): ADDON-57949 Fixed the custom menu with style property issue

- src/main/webapp/pages/Input/InputPage.jsx
**Steps to reproduce:**
- In the Inputs tab, set `style: page` in the globalConfig file
- Click on the tab
- Click on Add, Edit, or Clone button
- It will open a form on the new page
- Click on the Cancel button
- Now change the tab
- It's opening a new page instead of opening a tabs content (Table view)
> fix(CODE): ADDON-57152 Fixed tabs clicking issue when style is set to page

- src/main/webapp/components/TextAreaComponent.jsx
- src/main/webapp/constants/ControlTypeMap.js
- src/main/webapp/schema/schema.json
Added support for Textarea filed. 
Validators, options, help, defaultValue, etc. fields are supported to use textarea component/filed.
GlobalConfig json file looks like this:
```
{
"type": "textarea",
"label": "Textarea Field",
"field": "textarea_field",
"help": "Help message",
"options": {
"rowsMin": 3,
"rowsMax": 15
},
"required": true
}
```
> feat(CODE): ADDON-57044 Added new support for Textarea field

- src/main/webapp/components/table/CustomTable.jsx
**Previously:**
**If we have more inputs, this table will now have a fixed header.**
> feat(CODE): ADDON-58506 Improve table using docked property

- src/main/webapp/components/FileInputComponent.jsx
- src/main/webapp/constants/ControlTypeMap.js
- src/main/webapp/constants/constant.js
- src/main/webapp/constants/messageDict.js
- src/main/webapp/schema/schema.json
- src/main/webapp/util/Validator.js
- src/main/webapp/util/uccConfigurationValidators.js
This is how we can use file input in the global config file -
```
{
"type": "file",
"label": "Service Account's certificate",
"help": "Content of the service account's downloaded JSON key.",
"field": "certificate",
"options": {
"fileSupportMessage": "We only support json file"
},
"validators": [
{
"type": "file",
"supportedFileTypes": ["json"]
}
],
"required": true,
"encrypted": true
}
```
**Notes:**
- We only support JSON file
- Maximum file size is 500KB
**Output:**
> feat: ADDON-57046: Added file input component

- .eslintrc.js
- .github/workflows/build-test-release.yml
- .husky/pre-commit
- package.json
- yarn.lock
es-lint and prettier have been configured. I also used the [husky](https://typicode.github.io/husky/#/) to set up pre-commit.
**Note**: Depending on how Husky is configured, before committing the code, it will execute the es-lint and prettier commands to validate and format the code. If there is a problem, we will receive an error and refuse the commits.
> ADDON-58896 Setup es-lint & prettier and configured pre-commit hook

- src/main/webapp/components/BaseFormView.jsx
**Before :** 
https://user-images.githubusercontent.com/62089106/208842731-347aa191-60b7-4732-9614-656448fdc1fa.mov
**After did the code change :** 
https://user-images.githubusercontent.com/62089106/208842815-4bc5f1a7-88e7-433f-8492-68a0a0c29655.mov
> fix ADDON-58867: Fixed dropdown reset value while clicking on X button

- src/main/webapp/components/BaseFormView.jsx
- src/main/webapp/components/FileInputComponent.jsx
File input is only sending the fileContent now, instead of sending the object which is incorrectly stored in the backend (like, `[object Object]`).
> ADDON-57046: Sending file content as a string in the payload

- src/main/webapp/components/table/CustomTable.jsx
- src/main/webapp/components/table/CustomTableRow.jsx
- src/main/webapp/schema/schema.json
**Jira Link** - https://splunk.atlassian.net/browse/ADDON-58705
Now the UCC should take care of the actions given in the global config file and accordingly it will render the **Actions button** in the table. For Example -
**Global config snippet:**
```
"inputs": {
"table": {
"actions": [
"edit"
],
"header": [
{
"label": "Name",
"field": "name"
},
......
......
]
}
}
```
**Output:**
> **Note:** Currently, the actions list supports "edit," "delete," "clone," and "enable," but **enable** is deprecated and will be removed in the upcoming release of the ucc-gen.
> fix: ADDON-58705 Table action buttons are dynamic from the global config file

- src/main/webapp/components/table/CustomTable.jsx
- src/main/webapp/components/table/TableWrapper.jsx
We did some code changes as part of this Jira - [ADDON-47627](https://splunk.atlassian.net/browse/ADDON-47627).
I am reverting the code changes for the same and providing the alternative solution here.
**Solution:**
To resolve the sorting problem, developers needs to change the field name from **serviceName** to **serviceTitle** and remove the mapping entirely from the global config file. It should also display the correct **Input Type** name in the column, and the sorting issue should be resolved.
Like this - 
```
{
"field": "serviceTitle",
"label": "Input Type"
}
```
> fix: ADDON-59459 revert the code changes of ADDON-47627 jira

- src/main/webapp/components/BaseFormView.jsx
- src/main/webapp/components/ControlWrapper.jsx
- src/main/webapp/components/SingleInputComponent.jsx
**Jira Link** - https://splunk.atlassian.net/browse/ADDON-59779
We are modifying the code for the single input component. The changes are that if that field is marked as required, the option to clear the field value is no longer displayed. Otherwise, we'll have a clear button to remove the field value.
If a required field is not specified in the globalConfig file, we internally mark it as optional and display a clear button along with a select box.
Here is the output when we have required to false (or the complete required field is not present in the globalConfig file) -
When required set to true-
> refactor: ADDON-59779 Refactored single input component

- src/main/webapp/components/BaseFormView.jsx
[ADDON-62193](https://splunk.atlassian.net/browse/ADDON-62193)
* Encoded the redirect_uri value when opening up the popup in the OAuth workflow for asking the user consent
**Reason for the changes:**
* In the Box add-on, we encountered the issue when having the IP address in the redirect_uri, it is throwing the 403 forbidden error for the below type of request.
* `https://account.box.com/api/oauth2/authorize?response_type=code&client_id=<client_id>&redirect_uri=https://10.0.16.0`
* The above URL was working as expected previously but due to the behavior change at the Box platform for the redirect_uri having the IP address, now it is no longer working.
* If we encode the redirect_uri then the OAuth workflow would work as expected.
* …
> fix: ADDON-62193 encoded the redirect_uri upon opening the popup

- src/main/webapp/components/CustomMenu.jsx
- src/main/webapp/components/MenuInput.jsx
- src/main/webapp/schema/schema.json
**Jira Link -** https://splunk.atlassian.net/browse/ADDON-62948
Introduced a new way to add **subTitle** in the service name so it will look like this -
global config snippet -
> "services": [
{
"entity": [],
"name": "box_service",
"title": "Historical Querying Inputs",
"subTitle": "(Recommended)"
}
]
Also did a minor modification in the code so that developer can utilise **custom menu** and **groupsMenu** feature together.
> We will raise another PR to update ucc doc accordingly
> feat: ADDON-62948 Added support for subTitle field in service

- package.json
- src/main/webapp/components/ErrorBoundary.jsx
- src/main/webapp/components/SingleInputComponent.jsx
- src/main/webapp/components/table/CustomTableRow.jsx
- yarn.lock
JIRA Link - https://splunk.atlassian.net/browse/ADDON-64842
- added missing dependencies to package.json that were installed transitive. 
- added missing direct dependency react-icon (how did it work before?)
- fixed paths that changed since v3 for react-icons
- fixed vulnerability CVE-2022-25883 fossa was complaining about
> chore(deps): ADDON-64842 fix CI

- jest.setup.js
- package.json
- src/main/webapp/mocks/server-handlers.js
- src/main/webapp/mocks/server-response.js
- src/main/webapp/mocks/server.js
- yarn.lock
The JIRA link - https://splunk.atlassian.net/browse/ADDON-64637
Since the app is very coupled with API, it's better to bring ability to mock network requests (for unit and integration testing at first).
- Docs - [mswjs.io](https://mswjs.io/)
- [npm](https://npmjs.com/package/msw)
- High-level analysis on [socket.dev](socket.dev/npm/package/msw)
This changes are required for adding integration testing for components, like `InputPage.jsx`.
> chore(deps): ADDON-64637 add msw for API mocking

- src/main/webapp/components/MenuInput.test.jsx
- src/main/webapp/pages/Input/InputPage.test.jsx
- src/main/webapp/tests/helpers.js
- src/main/webapp/util/__mocks__/mockUnifiedConfig.js
- src/main/webapp/util/__mocks__/util.js
The JIRA link - https://splunk.atlassian.net/browse/ADDON-64637
Added unit/integration tests MenuInput and InputPage components.
I have question about the following functionality:
[CustomMenu.jsx:22](https://github.com/splunk/addonfactory-ucc-base-ui/blob/f40b95de8aa868cf3bdb87208eb0827d93753ee7/src/main/webapp/components/CustomMenu.jsx#L22)
```ts
if (services && customMenuField && !groupsMenu) {
customControl.render();
}
```
we don't render custom component if we don't have groupsMenu.
It is covered with test: `should render CustomMenu wrapper with groupsMenu without rendering underlying custom component`
> test: ADDON-64637 add tests for InputPage and MenuInput

- .github/workflows/build-test-release.yml
[GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Before
After
> ci(build-test-release.yml): replace deprecated set-output command

- src/main/webapp/components/MenuInput.jsx
- src/main/webapp/components/MenuInput.test.jsx
- src/main/webapp/pages/Input/InputPage.jsx
- src/main/webapp/pages/Input/InputPage.test.jsx
The JIRA Link: [ADDON-64637](https://splunk.atlassian.net/browse/ADDON-64637)
I have changed the argument of `handleRequestOpen` prop of MenuInput from
```ts
handleRequestOpen(serviceName: string, groupName: string);
```
to
```ts
handleRequestOpen(params: { serviceName: string, groupName?: string, input?: string });
```
The input value is required in InputPage component for setting URL QueryParam
> fix: ADDON-64637 add input value to query for menu navigation

- .addonmatrix
- .github/workflows/build-test-release.yml
PR adds ability to run e2e tests from the [addonfactory-ucc-generator](https://github.com/splunk/addonfactory-ucc-generator) repository
> ci: add job for running ci tests

- src/main/webapp/components/BaseFormView.jsx
- src/main/webapp/components/table/CustomTableControl.jsx
Addressing the issue found by [security-sast-semgrep](https://github.com/splunk/addonfactory-ucc-base-ui/actions/runs/6038233137/job/16384170975)
> chore(BaseFormView): fix exposing sensitive info in stack traces

- src/main/webapp/components/BaseFormView.jsx
- src/main/webapp/components/MultiInputComponent.jsx
- src/main/webapp/components/SingleInputComponent.jsx
- src/main/webapp/components/TextAreaComponent.jsx
- src/main/webapp/components/TextComponent.jsx
- src/main/webapp/components/table/TableFilter.jsx
- src/main/webapp/constants/messageDict.ts
**Jira Link -** https://splunk.atlassian.net/browse/ADDON-61204
We have deprecated support for the "placeholder" attribute (as announced by Splunk UI.) It won't be breaking change.
Users can still use the "placeholder" property in the global config file, but it won't have any impact on the UI. As a result, the placeholder will not be visible anymore. Instead of that, we recommend using the [help](https://splunk.github.io/addonfactory-ucc-generator/entity/) property to display any additional message along with the component.
Slack thread link for ref - https://splunk.slack.com/archives/C8R00E97S/p1689831102691599
> fix: ADDON-61204 Remove support of placeholder property

- webpack.config.js
It does not affect end users, source maps are loaded only when browser DevTools is open. It makes debugging of addons much easier.
> chore: add JS source maps to production build

- src/main/webapp/components/MenuInput.jsx
- src/main/webapp/pages/Input/InputPage.jsx
- src/main/webapp/pages/Input/InputPage.test.tsx
- src/main/webapp/util/__mocks__/mockUnifiedConfig.ts
[ADDON-65006](https://splunk.atlassian.net/browse/ADDON-65006)
The value of `input` is taken from `groupName` field of globalConfig (if present).
The menu itself (for reference):
Click on _S3 Access Logs_ -> _SQS-Based S3_ opens the URL with populated `input` query: 
For a root-level menu item the `input` value is not populated:
the `input` value provided by custom component by calling `navigator` function takes precedence. 
Related PR: splunk/splunk-add-on-for-amazon-web-services#1053
> feat: ADDON-65006 add group name to URL when redirecting with Menu
