src/main/webapp/components/table/CustomTable.jsx, src/main/webapp/pages/Configuration/ConfigurationPage.jsx
Jira: [ADDON-35571](https://jira.splunk.com/browse/ADDON-35571)
=> fix(routing): handle record param deletion on wrong tab and fix tab change due to missing dep in useCallback

package.json, src/main/webapp/components/BaseFormView.jsx, src/main/webapp/components/EntityPage.jsx, src/main/webapp/pages/entry_page.jsx, src/main/webapp/pages/style.scss, webpack.config.js
JIRA Ticket: https://jira.splunk.com/browse/ADDON-35553
=> feat: Added support of group fields

.babelrc.js, data/redirect_page.js, package.json, src/main/resources/splunk/appserver/templates/redirect.html, src/main/resources/splunk/default/data/ui/views/redirect.xml, src/main/webapp/components/BaseFormView.jsx, src/main/webapp/constants/oAuthErrorMessage.js, yarn.lock
- Implemented O-Auth Functionality
[jira link](https://jira.splunk.com/browse/ADDON-35569)
=> Feature/addon 35569 ucc splunk UI migration oauth implementation

src/main/webapp/pages/entry_page.jsx, webpack.config.js
-Added lazy loading for inputPage and configuration page
-Added pre-loading to save extra time
[jira link](https://jira.splunk.com/browse/ADDON-35570)
=> ADDON-35570:Added pre-loading and  lazy loading

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/components/DeleteModal.jsx, src/main/webapp/components/MultiInputComponent.jsx, src/main/webapp/components/SingleInputComponent.jsx, src/main/webapp/components/TextComponent.jsx, src/main/webapp/components/table/CustomTable.jsx, src/main/webapp/components/table/CustomTableStyle.jsx, src/main/webapp/components/table/TableHeader.jsx, src/main/webapp/components/table/TableWrapper.jsx, src/main/webapp/pages/Configuration/ConfigurationPage.jsx, src/main/webapp/pages/Input/InputPage.jsx, src/main/webapp/pages/entry_page.jsx, src/main/webapp/pages/style.css, src/main/webapp/util/axiosCallWrapper.js, src/main/webapp/util/messageUtil.js, yarn.lock
Jira: https://jira.splunk.com/browse/ADDON-35571
Bug fixes:
- eslint/prop-types failure fixes
- `axiosCallWrapper` was using undefined variable in some cases
- table filter was using all the fields received from endpoint response
- clear encrypted fields at edit/clone action on entities
- handle form save when no response received from server or parsing fails
- add message when no records found in table
- revert to default Splunk background color and rename file extension from `.scss` to `.css`
- remove toast messages on toggle action
- use messageDict for constants
- fix message displayed in `DeleteModal` based on page
=> ADDON-35571: bug fixes

src/main/webapp/components/CustomMenu.jsx, src/main/webapp/pages/Input/InputPage.jsx, src/main/webapp/pages/style.scss
JIRA Ticket: https://jira.splunk.com/browse/ADDON-35556
=> feat: Custom menu implementation

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/schema/schema.json, src/main/webapp/util/Validator.js
-Added validation for name field as per old UCC
=> Added validation for name field

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/components/table/CustomTableControl.jsx
Jira: https://jira.splunk.com/browse/ADDON-36730
- fix: custom cell/row should re-render when a row is updated
- fix: pass row and field to custom cell/row for processing on re-render
=> ADDON-36730: Custom UI extension fixes

src/main/webapp/components/MultiInputComponent.jsx, src/main/webapp/components/RadioComponent.jsx, src/main/webapp/components/SingleInputComponent.jsx, src/main/webapp/components/TextComponent.jsx, src/main/webapp/components/table/CustomTableRow.jsx
Jira: https://jira.splunk.com/browse/ADDON-36747
- fix: updated textbox width and changed field value for custom cell
- fix: added comment
=> ADDON-36747 Bug Fixes

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/components/ComboBoxWrapper.jsx, src/main/webapp/components/ControlWrapper.jsx, src/main/webapp/components/DeleteModal.jsx, src/main/webapp/components/SingleInputComponent.jsx, src/main/webapp/components/TextComponent.jsx, src/main/webapp/util/messageUtil.js
Jira: https://jira.splunk.com/browse/ADDON-36747
- fix: bug fixes related to input and configuration page
- fix: updated review changes
- fix: handled warnings and updated the changes
- fix: formatted the code
- fix: changed let to const to fix eslint error
Bugs Fixed (Input Page) :
- No placeholders for All the field of Create New Input Form.
- There is no help text link for configuring a new account in the input form.
- In input, if an account is not configured then there should be msg like "Missing account configuration" Instead of "Missing configuration".
- After updating input it still opens the same edit input box.
- After updating Account in Input it still showing unconfigured account in the Input table.
Bugs Fixed (Configuration Page) :
- No placeholders for All the field of Add …
=> ADDON-36747 bug fixes related to input and configuration page

src/main/webapp/components/MarkdownMessage.jsx, src/main/webapp/components/table/CustomTable.jsx
=> fix: eslint failures

src/main/webapp/util/Validator.js
Jira: https://jira.splunk.com/browse/ADDON-37153
- fix: change in order of validations
=> ADDON-37153 Bug Fixes

src/main/webapp/schema/schema.json
Jira: https://jira.splunk.com/browse/ADDON-37376
Changes:
- Updated schema to support placeholder in `globalConfig.json` for OAuth fields
=> feat: support placeholder in `globalConfig.json` for oauth fields

src/main/webapp/components/BaseFormView.jsx
Jira: https://jira.splunk.com/browse/ADDON-37153
- fix: remove redirect_url field from conf file
=> ADDON-37153: Prevent passing `redirect_url` field used in OAuth to backend conf file

src/main/webapp/components/table/TableExpansionRow.jsx
Jira: https://jira.splunk.com/browse/ADDON-37153
- Removed extra rows which are empty in moreInfo
=> ADDON-37153: Remove extra rows which are empty in moreInfo

src/main/webapp/components/ConfigurationFormView.jsx, src/main/webapp/components/EntityModal.jsx, src/main/webapp/components/SingleInputComponent.jsx, src/main/webapp/components/table/CustomTableRow.jsx
Jira: https://jira.splunk.com/browse/ADDON-36754
Changes:
- Enhanced few components with selectors for ease of testing.
=> fix(smartx): add selectors for better testing

webpack.config.js
Follow up fix for: https://github.com/splunk/addonfactory-ucc-base-ui/pull/33
=> fix: add notice in release tarball

src/main/webapp/components/table/CustomTable.jsx
Jira: https://jira.splunk.com/browse/ADDON-37812
Changes:
- Remove dependency on inputs config when configuration page is visited.
Fixes https://github.com/splunk/addonfactory-ucc-base-ui/issues/37.
=> fix: inputs dep in configuration page

THIRDPARTY.npm, src/main/webapp/components/PlaceholderComponent.jsx, src/main/webapp/constants/ControlTypeMap.js
Jira: https://jira.splunk.com/browse/ADDON-37812
Changes:
- Added support for placeholder entity type
Screenshot of the form with placeholder type entity:
Example config for placeholder:
```
{
"label": "Source",
"type": "placeholder",
"field": "source",
"options": {
"defaultValue": "Example Placeholder"
}
}
```
=> feat: support placeholder entity type

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/util/util.js
Jira: https://jira.splunk.com/browse/ADDON-37993
Changes:
- Added dependent field resolution logic in form constructor as well to populate fields on form creation
=> fix: load dependent fields on form create

src/main/webapp/components/BaseFormView.jsx
Jira: https://jira.splunk.com/browse/ADDON-38274
- Cleared fields for other authentication methods when using one
=> Cleared fields for other authentication methods when using one

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/components/SingleInputComponent.jsx
Jira: https://jira.splunk.com/browse/ADDON-38549
=> fix: enforce logic for displaying clear button for singleselect when its disabled

src/main/webapp/components/BaseFormView.jsx
Jira: https://jira.splunk.com/browse/ADDON-38581
=> fix: fallback to latest form state if resthandler skips some table fields from response

src/main/webapp/components/BaseFormView.jsx
Jira: https://jira.splunk.com/browse/ADDON-39022
=> fix: default to `basic` oauth_type if `undefined` to handle upgrade scenario for some add-ons

src/main/webapp/components/MultiInputComponent.jsx, src/main/webapp/components/SingleInputComponent.jsx, src/main/webapp/components/table/TableWrapper.jsx
Jira: https://jira.splunk.com/browse/ADDON-39044
=> fix: pass `count` query param in rest to overcome default thirty records limit

src/main/webapp/components/table/TableWrapper.jsx
Jiras: 
- https://jira.splunk.com/browse/ADDON-39125
- https://jira.splunk.com/browse/ADDON-39208
=> fix: parse boolean of `disabled` before setting it in state and handle `undefined` value in table sort

.github/dependabot.yml, .github/workflows/build-test-release.yml, .gitignore
This PR updates Github Actions dependencies.
=> ci: update dependencies

src/main/resources/splunk/default/data/ui/nav/default_no_input.xml
Adding this to be able to remove defusedxml from ucc-gen.
=> feat: add new default XML file without input

src/main/webapp/util/script.js
- Added support to use yaml format. So, **we can use globalConfig.json or globalConfig.yaml file**
=> ADDON-56381: Added support for YAML file

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/components/ControlWrapper.jsx
Fixed the issue to update the placeholder dynamically
=> fix(code): ADDON-46211 Fixed the issue to set the dynamic placeholder

.github/workflows/build-test-release.yml, package.json, yarn.lock
PR Links:
1. https://github.com/splunk/addonfactory-ucc-base-ui/pull/92
2. https://github.com/splunk/addonfactory-ucc-base-ui/pull/95
3. https://github.com/splunk/addonfactory-ucc-base-ui/pull/122
4. https://github.com/splunk/addonfactory-ucc-base-ui/pull/96
5. https://github.com/splunk/addonfactory-ucc-base-ui/pull/99
6. https://github.com/splunk/addonfactory-ucc-base-ui/pull/106
7. https://github.com/splunk/addonfactory-ucc-base-ui/pull/102
=> chore(deps): ADDON-57161 Version bump by dependabot

src/main/webapp/components/table/CustomTable.jsx, src/main/webapp/components/table/TableExpansionRow.jsx, src/main/webapp/components/table/TableFilter.jsx, src/main/webapp/components/table/TableHeader.jsx, src/main/webapp/components/table/TableWrapper.jsx, src/main/webapp/pages/Input/InputPage.jsx, src/main/webapp/schema/schema.json
=> feat: ADDON-57152 added tabs feature in the Inputs page

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/components/EntityModal.jsx, src/main/webapp/components/EntityPage.jsx, src/main/webapp/components/MenuInput.jsx, src/main/webapp/pages/Input/InputPage.jsx, src/main/webapp/schema/schema.json
**Example usage below:**
**Output :**
=> ADDON-58758: Implement multilevel dropdown component

src/main/webapp/util/Validator.js
The screenshot below shows how it validates the fields when we enter a blank space and submit the form -
=> feat: ADDON-58944 Validations have been updated to ensure that the field should not contain empty space

src/main/webapp/components/ConfigurationFormView.jsx, src/main/webapp/components/DeleteModal.jsx, src/main/webapp/components/EntityModal.jsx, src/main/webapp/components/EntityPage.jsx, src/main/webapp/components/ErrorModal.jsx, src/main/webapp/components/MenuInput.jsx, src/main/webapp/components/SingleInputComponent.jsx, src/main/webapp/components/table/TableHeader.jsx, src/main/webapp/components/table/TableWrapper.jsx, src/main/webapp/pages/EntryPageStyle.js, src/main/webapp/pages/entry_page.jsx
- Consistent button size across the app
- Wait spinner size updated
=> style: ADDON-59460 UI UX Improvements

src/main/webapp/components/ErrorModal.jsx, src/main/webapp/components/MenuInput.jsx, src/main/webapp/constants/messageDict.js
> Before code changes
> 
> https://user-images.githubusercontent.com/62089106/219556260-264cd0e8-babf-4c9e-bae3-7b1b6121981c.mov
> After code changes
> 
> https://user-images.githubusercontent.com/62089106/219556221-c943e129-842f-427d-bd90-cae60f598d1d.mov
>
=> refactor: ADDON-59948 Fix the UI/UX for multi-level menu

src/main/webapp/components/ConfigurationTable.jsx, src/main/webapp/components/ErrorModal.jsx, src/main/webapp/components/table/CustomTable.jsx, src/main/webapp/pages/Input/InputPage.jsx
This is breaking a UI tests [here](https://github.com/splunk/addonfactory-ucc-generator/actions/runs/4374793671/jobs/7654706892).
=> fix: revert 0497ac4e2e961ac141307a3ab7e6790e9bd31705

package.json, src/main/webapp/tests/Components/FileInputComponent.test.jsx, yarn.lock
Jira Link - https://splunk.atlassian.net/browse/ADDON-61331
=> test: ADDON-61331 test cases has been added for file input component

src/main/webapp/components/ControlWrapper.jsx
Jira - https://splunk.atlassian.net/browse/ADDON-61203
=> ADDON-61203: Append asterisk sign before label 

package.json, src/main/webapp/components/ControlWrapper.jsx, src/main/webapp/tests/Components/FileInputComponent.test.jsx, yarn.lock
* Test cases for the file input component
* Add asterisk sign for required fields
=> feat: release v1.24.0

src/main/webapp/schema/schema.json
This will allow us to define panels that we want to use in the dashboard.
=> feat: add DashboardPanel-s to dashboard

src/main/webapp/pages/style.css
Jira Link - https://splunk.atlassian.net/browse/ADDON-61381
=> fix: ADDON-61381 Fixed the design issue in Safari browser

src/main/webapp/components/MenuInput.jsx
Jira - https://splunk.atlassian.net/browse/ADDON-62948
=> refactor: ADDON-62948 Added support for subTitle field in service

src/main/webapp/components/BaseFormView.jsx, src/main/webapp/components/CheckboxGroupsComponent.jsx, src/main/webapp/components/ControlWrapper.jsx, src/main/webapp/components/StyledComponent.jsx, src/main/webapp/constants/ControlTypeMap.js, src/main/webapp/schema/schema.json, src/main/webapp/util/util.js
**Jira -** https://splunk.atlassian.net/browse/ADDON-61556
Frontend changes has been done.
Backend Changes Jira - https://splunk.atlassian.net/browse/ADDON-64823
Doc Changes Jira - https://splunk.atlassian.net/browse/ADDON-64824
We've introduced a new entity type named **checkboxGroups** along with the addition of the **CheckboxGroupsMetadata** property. This new property allows for the utilization of this entity in a grouped format.
The following screenshot presents a global config snippet that demonstrates how to utilize checkbox group.
> The detailed documentation will be done as a separate task.
**Checkbox With Groups Feature:**
**Without Grouping Feature: (If 'groups' property is not specified inside the 'CheckboxGroupsMetadata' property)**
**This is how payload will pass to the …
=> feat: ADDON-61556 Introduced checkbox group component

src/main/webapp/schema/schema.json
the app expects these fields as required
=> fix(schema.json): add required configuration and inputs fields
